/*1. What are the details of all cars purchased in the year 2022?*/

SELECT c.car_id, c.make, c.type, c.style, c.cost_$, s.purchase_date
FROM cars c
	INNER JOIN sales s ON c.car_id = s.car_id
WHERE YEAR(s.purchase_date) = "2022";
                
/*2. What is the total number of cars sold by each salesperson?*/

SELECT s.salesman_id, sp.name, COUNT(*) AS Number_Of_Car_Sold
FROM sales s 
	JOIN salespersons sp ON s.salesman_id = sp.salesman_id
GROUP BY s.salesman_id, sp.name
ORDER BY s.salesman_id;

/*3. What is the total revenue generated by each salesperson?*/

SELECT sp.name, SUM(c.cost_$) AS Total_revenue_generated
FROM sales s 
	INNER JOIN salespersons sp ON s.salesman_id = sp.salesman_id
	INNER JOIN cars c ON s.car_id = c.car_id
GROUP BY sp.name;

/*4. What are the details of the cars sold by each salesperson?*/

SELECT sp.salesman_id, sp.name, c.car_id, c.make, c.type, c.style, c.cost_$
FROM sales s 
	INNER JOIN cars c ON s.car_id = c.car_id
	INNER JOIN salespersons sp ON s.salesman_id = sp.salesman_id;
    
/*5. What is the total revenue generated by each car type?*/

SELECT c.type, SUM(c.cost_$) AS Total_revenue_generated
FROM cars c 
	INNER JOIN sales s ON c.car_id = s.car_id
GROUP BY c.type
ORDER BY c.type;

/*6. What are the details of the cars sold in the year 2021 by salesperson 'Emily Wong'?*/

SELECT sp.name, c.car_id, c.make, c.type, c.style, c.cost_$, s.purchase_date
FROM sales s 
	INNER JOIN cars c ON s.car_id = c.car_id
	INNER JOIN salespersons sp ON s.salesman_id = sp.salesman_id
WHERE sp.name = "Emily Wong" AND YEAR(s.purchase_date) = "2021";

/*7. What is the total revenue generated by the sales of hatchback cars?*/

SELECT c.style, SUM(c.cost_$) AS Total_revenue_generated
FROM sales s 
	INNER JOIN cars c ON s.car_id = c.car_id
GROUP BY c.style
HAVING c.style = "Hatchback";

/*8. What is the total revenue generated by the sales of SUV cars in the year 2022?*/

SELECT c.style, SUM(c.cost_$) AS Total_revenue_generated
FROM cars c 
	INNER JOIN sales s ON c.car_id = s.car_id
WHERE c.style = "SUV" AND YEAR(s.purchase_date) = "2022"
GROUP BY c.style;

/*9. What is the name and city of the salesperson who sold the most number of cars in the year 2023?*/

SELECT sp.name, sp.city, COUNT(*) AS Most_cars_sold
FROM salespersons sp
	INNER JOIN sales s ON sp.salesman_id = s.salesman_id
WHERE YEAR(s.purchase_date) = "2023"
GROUP BY sp.name, sp.city
ORDER BY COUNT(*) DESC
LIMIT 1;

/*10. What is the name and age of the salesperson who generated the highest revenue in the year 2022?*/

SELECT sp.name, sp.age, SUM(c.cost_$) AS Highest_revenue_generated
FROM sales s 
	INNER JOIN cars c ON s.car_id = c.car_id
	INNER JOIN salespersons sp ON s.salesman_id = sp.salesman_id
WHERE YEAR(s.purchase_date) = "2022"
GROUP BY sp.name, sp.age
ORDER BY SUM(c.cost_$) DESC
LIMIT 1;


	